### ISSUE TITLE
Course ID not correct

### ISSUE THREAD

**Issue by SaraEnergy** [Damian1234523/Cheetah#15]
When opening a course, it directs to the wrong course => wrong course ID..

**Comment by Damian1234523** [comment]
It seems like while building the link to either the course or lecturer the id's are being switched. It must be a problem with the link generator in general. I'm investigating...

**Comment by Damian1234523** [comment]
problem solved for course links in universities. lecturer link is more complicated because at that point accessing th id of univerity would need a atabsaquerry why leads all the way back to university. there must be a way to read the university paramter from a url like this: http://localhost:3000/universities/8/courses/23
that would make a cleaner solution for the course link in university too.

**Comment by Damian1234523** [comment]
Fixed the link generator using the params method to dertemine the id of university from url. To make the code less ugly i tried to use params for the other ids too but it failed. However problem solved.
